version: "3.7"

services:
  dockerized-react:
    container_name: dockerized-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=development
