name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        node_version: 'lts/*'
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install Dependencies
      run: npm install
    - name: Build Script
      run: npm run build
    
